In [ ]:
from paddleocr import PaddleOCR
import cv2
import numpy as np
# Also switch the language by modifying the lang parameter
ocr = PaddleOCR(lang="en") # The model file will be downloaded automatically when executed for the first time
img_path ='../bien-so-xe_0401085240.jpg'
result = ocr.ocr(img_path)
# Recognition and detection can be performed separately through parameter control
# result = ocr.ocr(img_path, det=False)  Only perform recognition
# result = ocr.ocr(img_path, rec=False)  Only perform detection
# Print detection frame and recognition result
for line in result:
    print(line)
 
# Visualization
mat = cv2.imread(img_path)
 
boxes = [line[0] for line in result[0]]
txts = [line[1][0] for line in result[0]]
scores = [line[1][1] for line in result[0]]
for box in boxes:
    pts = np.array(box,np.int32)
    pts = pts.reshape((-1, 1, 2))
    mat = cv2.polylines(
        img=mat,
        isClosed=True,
        pts=[pts],
        color = (255, 0, 0)
        )
# print(boxes)
cv2.imshow("result", mat)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np
id = "../Bien_so.mp4"
vid = cv2.VideoCapture(id)
while(vid.isOpened()):
    ret, frame = vid.read()
    print(frame.shape)
    if ret:
        cv2.imshow("frame", frame)
        cv2.waitKey(1)
    else:
        break
    print(frame.shape)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        cv2.destroyAllWindows()
        break
cv2.destroyAllWindows()
vid.release()

In [4]:
char_list =  '0123456789ABCDEFGHKLMNPRSTUVXYZ'
txt = ["230","44F3"]
if(len(txt) == 2):
    out = ""
    for i in txt[0]:
        if(i in char_list):
            out += i 
    for j in txt[1]:
        if(j in char_list):
            out += j 
    print(out)

23044F3


In [5]:
(480, 852, 3)

In [3]:
def get_detect(mat):
    result = ocr.ocr(mat)
    
    boxes = [line[0] for line in result[0]]
    txt = [line[1][0] for line in result[0]]
    scores = [line[1][1] for line in result[0]]
    for box in boxes:
        pts = np.array(box,np.int32)
        pts = pts.reshape((-1, 1, 2))
        mat = cv2.polylines(
            img=mat,
            isClosed=True,
            pts=[pts],
            color = (255, 0, 0)
            )
    return mat,txt


In [7]:
mat = cv2.imread("./download.jpg")

In [ ]:
from keras.models import model_from_json

In [5]:

img,txt = get_detect(mat)

AssertionError: 

In [8]:
cv2.imshow("result", mat)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(txts)

error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:967: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'


In [28]:
pts = np.array([[25, 70], [25, 160],
                [110, 200], [200, 160],
                [200, 70], [110, 20]],
               np.int32)
 
pts = pts.reshape((-1, 1, 2))
print(pts)

[[[ 25  70]]

 [[ 25 160]]

 [[110 200]]

 [[200 160]]

 [[200  70]]

 [[110  20]]]


In [10]:
for box in boxes:  
    print(box[0])

[[66.0, 2.0], [610.0, 0.0], [612.0, 241.0], [68.0, 245.0]]


In [3]:
for box in boxes:    
    top_left     = ((box[0][0][0]), (box[0][0][1]))
    bottom_right = ((box[2][0]), (box[2][1]))

IndexError: list index out of range

In [19]:
x = []
for line in result[0]:
    x.append(line)
print(x)

[[[[66.0, 2.0], [610.0, 0.0], [612.0, 241.0], [68.0, 245.0]], ('99-H7', 0.9757689237594604)], [[[79.0, 232.0], [590.0, 237.0], [587.0, 454.0], [76.0, 453.0]], ('7060', 0.9987074136734009)]]


In [23]:
print(boxes)
print(txts)
print(scores)

[[[66.0, 2.0], [610.0, 0.0], [612.0, 241.0], [68.0, 245.0]], [[79.0, 232.0], [590.0, 237.0], [587.0, 454.0], [76.0, 453.0]]]
['99-H7', '7060']
[0.9757689237594604, 0.9987074136734009]


In [29]:
for box in boxes:
    print(box)
    pts = np.array(box,
               np.int32)
    print(pts)

[[66.0, 2.0], [610.0, 0.0], [612.0, 241.0], [68.0, 245.0]]
[[ 66   2]
 [610   0]
 [612 241]
 [ 68 245]]
[[79.0, 232.0], [590.0, 237.0], [587.0, 454.0], [76.0, 453.0]]
[[ 79 232]
 [590 237]
 [587 454]
 [ 76 453]]


In [7]:
x = 10

In [17]:
n = 10
i = 0
d = 0
c = 1
f = 1
while i<n:
    print(f)
    f = d + c
    d = c
    c = f
    i+=1
    

1
1
2
3
5
8
13
21
34
55
